[package]
name = "blurhash-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blurhash = "0.2.0"
image = "0.24.6"

[profile.release]
strip = true
lto = true
codegen-units = 1